### ISSUE TITLE
如何自行打包？

### ISSUE THREAD

**Issue by Jikexiaobai** [james-curtis/chaoxing-sign-app#20]
看到作者在README中说到uni-app的APPID，应该支持打包IOS版本吧？想问下如何打包，自己是苹果手机，有企业证书

**Comment by eric-gitta-moore** [comment]
可以，应该用 HBuildX 有可视化的打包工具。但是不知道第三方模块是不是也支持 ios

**Comment by dcwang-lab** [comment]
> 看到作者在README中说到uni-app的APPID，应该支持打包IOS版本吧？想问下如何打包，自己是苹果手机，有企业证书

加我q 2099961945 教你弄

**Comment by Jikexiaobai** [comment]
close
